// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCTu_2F12g8w6IGUDw652bLRpM89bzYs9A",
      authDomain: "art-gallery-58f26.firebaseapp.com",
      projectId: "art-gallery-58f26",
      storageBucket: "art-gallery-58f26.firebasestorage.app",
      messagingSenderId: "485834652845",
      appId: "1:485834652845:web:b49fb3c236d452b3315a24",
      measurementId: "G-FX0BD98CF1"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzbUXSZg89r3p18ZdJUJ7xJxMzHdkTdc',
    appId: '1:485834652845:android:8b4fc71c8a394ac5315a24',
    messagingSenderId: '485834652845',
    projectId: 'art-gallery-58f26',
    storageBucket: 'art-gallery-58f26.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTu_2F12g8w6IGUDw652bLRpM89bzYs9A',
    appId: '1:485834652845:web:33c64546e3f7de91315a24',
    messagingSenderId: '485834652845',
    projectId: 'art-gallery-58f26',
    authDomain: 'art-gallery-58f26.firebaseapp.com',
    storageBucket: 'art-gallery-58f26.firebasestorage.app',
    measurementId: 'G-1KV987XZ0N',
  );
}
